**MACHINE LEARNING 23CSE301 LAB ACTIVITY 5 K NEAREST NEIGHBORS EXCERCISE 2**

ROHITH SUBRAMANIAN NITHYADEVI CH.SC.U4CSE24141

**Q2.** Calculate the distance between a new entry and other existing values using the Euclidean distance formula.

| Brightness | Saturation | Class |
|---|---|---|
| 40 | 20 | Red |
| 50 | 50 | Blue |
| 60 | 90 | Blue |
| 10 | 25 | Red |
| 70 | 70 | Blue |
| 60 | 10 | Red |
| 25 | 80 | Blue |

**Dataset:** The small table given in the exercise (built directly in this notebook), following the same programming approach used in Section 9.5 of the Lab Activity Book (Implementing KNN using Python).

### Importing Required Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

### Reading the Dataset (given in the exercise)

In [2]:
data = pd.DataFrame({
    'Brightness': [40, 50, 60, 10, 70, 60, 25],
    'Saturation': [20, 50, 90, 25, 70, 10, 80],
    'Class':      ['Red', 'Blue', 'Blue', 'Red', 'Blue', 'Red', 'Blue']
})
print(data.shape)
data

(7, 3)

   Brightness  Saturation Class
0          40          20   Red
1          50          50  Blue
2          60          90  Blue
3          10          25   Red
4          70          70  Blue
5          60          10   Red
6          25          80  Blue

### Checking for any null values in dataset

In [3]:
data.isnull().sum()

Brightness    0
Saturation    0
Class         0
dtype: int64

### Assigning Dependent and Independent Variables

In [4]:
x = data[['Brightness', 'Saturation']]
y = data['Class']

### New Entry to Classify

In [5]:
new_point = np.array([45, 45])
print('New entry (Brightness, Saturation): ', new_point)

New entry (Brightness, Saturation):  [45 45]

### Calculating the Euclidean Distance from the New Entry to every Existing Point

In [6]:
distances = np.sqrt(((x.values - new_point) ** 2).sum(axis=1))
dist_table = data.copy()
dist_table['Euclidean_Distance_to_New_Entry'] = distances
dist_table.sort_values(by='Euclidean_Distance_to_New_Entry')

   Brightness  Saturation Class  Euclidean_Distance_to_New_Entry
1          50          50  Blue                         7.071068
0          40          20   Red                        25.495098
4          70          70  Blue                        35.355339
5          60          10   Red                        38.078866
6          25          80  Blue                        40.311289
3          10          25   Red                        40.311289
2          60          90  Blue                        47.434165

### Training the Model using KNN (Euclidean / minkowski, p=2)

In [7]:
model = KNeighborsClassifier(n_neighbors=3, metric='minkowski', p=2)
model.fit(x, y)
predicted_class = model.predict([new_point])
print('Predicted class for the new entry', tuple(new_point), ':', predicted_class[0])

Predicted class for the new entry (np.int64(45), np.int64(45)) : Blue

d:\Python\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(